Repository wildfly/wildfly-proposals, pull requests merged in 2024-12, with the labels that each got.

#648 WFLY-19591 MicroProfile OpenAPI 4.0
  microprofile/WFLY-19591_MicroProfile_OpenAPI_4.0.adoc
Labels: stability-level/default

#641 [640][WFLY-19866] Add an analysis document for promoting the MicroPro…
  microprofile/WFLY-19866-promote-mp-rest-client-to-default.adoc
Labels: stability-level/default

#367 [WFLY-13412]:Add_Json_Merge_Patch_support
  jaxrs/WFLY-13122_Add_Json_Merge_Patch_support.adoc
Labels: stability-level/default

#665 [WFLY-19954] Add the vertx extension/subsystem from wildfly-vertx-feature-pack to WildFly Preview Feature Pack
  microprofile/WFLY-19954_Preview_Support_vertx_feature_pack.adoc
Labels: stability-level/preview

#624 [WFLY-19846] Migrate MP Tel 2.0 from PREVIEW to DEFAULT
  observability/WFLY-19846-promote-mp-tel-2-to-default.adoc
Labels: stability-level/default

#627 [WFLY-19855] WildFly Glow, introduce spaces to structure discovered Galleon feature-packs
  wf-galleon/WFLY-19855_glow_spaces.adoc
Labels: stability-level/community

#616 [WFLY-19588] Proposal for MicroProfile Platform 7.0
  microprofile/WFLY-19588_microprofile_platform_7.adoc
Labels: stability-level/default
